name: Dependency Check

on: 
  push:
    branches:
      - master
#    paths:
#    - 'Pipfile'

jobs:
  dep_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create python file
        run: printf 'import json\nimport re\n\npackage_regex = re.compile(r"(?<=\[packages\]\s)(.*)(?=\s\s)", flags=re.I|re.S)\nversion_regex = re.compile(r"(.*?)\s=\s\\"(.*?)\\"", flags=re.I)\n\nwith open("Pipfile", "r") as f:\n    pipfile = f. read()\n\npackages = package_regex.search(pipfile).group(0).split("\\n")\npackages = [version_regex.sub(r"\1\2", x) for x in packages]\n\nwith open("custom_components/office365calendar/manifest.json", "r+") as f:\n    _json = json.loads(f.read())\n    _json["requirements"] = packages\n    f.seek(0)\n    f.write(json.dumps(_json, indent=4))\n    f.truncate()' > dep.py
      - name: run python
        run: python3 dep.py
      - name: remove dep.py
        run: rm dep.py
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "Updated dependencies to latest version"
          title: "Manifest.json now matches Pipfile"
          author: "Bot McBotty <bot@steffensen.io>"
          branch: dependencies
          body: Please review and accept
      
