name: Dependency Check

on: 
  push:
    branches:
      - master
    paths:
    - 'Pipfile'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create python file
        run: printf 'import json\nimport re\n\npackage_regex = re.compile(r"(?<=\[packages\]\s)(.*)(?=\s\s)", f lags=re.I|re.S)\nversion_regex = re.compile(r"(.*?)\s=\s\"(.*?)\"", flags=re.I)\n\nwith open("Pipfile", "r") as f:\n    pipfile = f. read()\n\npackages = package_regex.search(pipfile).group(0).split("\\n")\npackages = [version_regex.sub(r"\1\2", x) for x in package s]\n\nwith open("manifest.json", "r+") as f:\n    _json = json.loads(f.read())\n    _json["requirements"] = packages\n    f.seek(0)\ n    f.write(json.dumps(_json, indent=4))\n    f.truncate()' > dep.py
      - name: run python
        run: python3 dep.py
      - name: remove dep.py
        run: rm dep.py
      
