name: Dependency Check

on: 
  push:
    branches:
      - master
    paths:
    - 'Pipfile'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bash
        uses: fnkr/github-action-git-bash@v1.1
        with: 
          args: "echo test > test.txt"
        
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "dependency update"
          title: "Updated dependcies"
          author: "Bot McBotty <bot@steffensen.io>"
          branch: dependency
          body: Please review and accept
