name: Black Check

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: create branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'black_formatter'
      - uses: actions/checkout@v2
        with:
          ref: black_formatter
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: "."
      - name: checkin
        uses: repo-sync/pull-request@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
